name: atividade Workflow 2.3

on:
    push:
jobs:
    primeiro-job:
        runs-on: ubuntu-latest
        env:
            CURSO: Integração Contínua
        steps:
            - run: echo "Primeiro passo"
            - name: Checkout
              uses: actions/checkout@v5
            - name: nome do curso
              run: echo "Curso; $CURSO"
            - name: usuário que executou o workflow 
              run: echo "Usuário; ${{github.actor}}"
            - name: nome do repositório
              run: echo "Repositório; ${{github.repository}}"
            - name: branch utilizada
              run: echo "Branch; ${{github.ref_name}}"

            
